development:
  server: "http://192.168.1.156:9292/faye"
  secret_token: "secret"
  port: 4443
  ssl: true
  ssl_key_file: /path/to/server.pem
  ssl_cert_file: /path/to/certificate_chain.pem
  environment: production
  rackup: private_pub.ru
test:
  server: "http://192.168.1.156:9292/faye"
  secret_token: "secret"
production:
  server: "http://192.168.1.156:9292/faye"
  secret_token: "efca6ac29b41650d68e9ad88ba10f02faa73b35e2d33a92b98b2eb20377856c6"
  signature_expiration: 3600 # one hour
  port: 4443
  ssl: true
  ssl_key_file: <ssl_key>.key
  ssl_cert_file: <ssl_cert>.crt
  environment: production
  rackup: private_pub.ru
  daemonize: true